//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic
    {
        public int id { get; set; }
        public string title { get; set; }
        public string series { get; set; }
        public string publisher { get; set; }
        public Nullable<int> issueNumber { get; set; }
    }
}
